import 'dart:convert';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../services/storage_service.dart';

class InvoiceSettings {
  final bool showCompanyInfo;
  final bool showInvoiceNumber;
  final bool showDueDate;
  final bool showBillingAddress;
  final bool showVatBreakdown;
  final bool showPaymentTerms;
  final bool showThankYouNote;
  final bool showFooter;
  final String thankYouNote;
  final String footerText;

  const InvoiceSettings({
    this.showCompanyInfo = true,
    this.showInvoiceNumber = true,
    this.showDueDate = true,
    this.showBillingAddress = true,
    this.showVatBreakdown = true,
    this.showPaymentTerms = true,
    this.showThankYouNote = true,
    this.showFooter = true,
    this.thankYouNote = 'Thank you for your business!',
    this.footerText = 'Generated by Survey Aide',
  });

  InvoiceSettings copyWith({
    bool? showCompanyInfo,
    bool? showInvoiceNumber,
    bool? showDueDate,
    bool? showBillingAddress,
    bool? showVatBreakdown,
    bool? showPaymentTerms,
    bool? showThankYouNote,
    bool? showFooter,
    String? thankYouNote,
    String? footerText,
  }) {
    return InvoiceSettings(
      showCompanyInfo: showCompanyInfo ?? this.showCompanyInfo,
      showInvoiceNumber: showInvoiceNumber ?? this.showInvoiceNumber,
      showDueDate: showDueDate ?? this.showDueDate,
      showBillingAddress: showBillingAddress ?? this.showBillingAddress,
      showVatBreakdown: showVatBreakdown ?? this.showVatBreakdown,
      showPaymentTerms: showPaymentTerms ?? this.showPaymentTerms,
      showThankYouNote: showThankYouNote ?? this.showThankYouNote,
      showFooter: showFooter ?? this.showFooter,
      thankYouNote: thankYouNote ?? this.thankYouNote,
      footerText: footerText ?? this.footerText,
    );
  }

  Map<String, dynamic> toJson() => {
    'showCompanyInfo': showCompanyInfo,
    'showInvoiceNumber': showInvoiceNumber,
    'showDueDate': showDueDate,
    'showBillingAddress': showBillingAddress,
    'showVatBreakdown': showVatBreakdown,
    'showPaymentTerms': showPaymentTerms,
    'showThankYouNote': showThankYouNote,
    'showFooter': showFooter,
    'thankYouNote': thankYouNote,
    'footerText': footerText,
  };

  factory InvoiceSettings.fromJson(Map<String, dynamic> json) => InvoiceSettings(
    showCompanyInfo: _b(json, 'showCompanyInfo', true),
    showInvoiceNumber: _b(json, 'showInvoiceNumber', true),
    showDueDate: _b(json, 'showDueDate', true),
    showBillingAddress: _b(json, 'showBillingAddress', true),
    showVatBreakdown: _b(json, 'showVatBreakdown', true),
    showPaymentTerms: _b(json, 'showPaymentTerms', true),
    showThankYouNote: _b(json, 'showThankYouNote', true),
    showFooter: _b(json, 'showFooter', true),
    thankYouNote: _s(json, 'thankYouNote', 'Thank you for your business!'),
    footerText: _s(json, 'footerText', 'Generated by Survey Aide'),
  );

  static bool _b(Map<String, dynamic> json, String key, bool def) {
    final v = json[key];
    if (v is bool) return v;
    return def;
  }

  static String _s(Map<String, dynamic> json, String key, String def) {
    final v = json[key];
    if (v is String) return v;
    return def;
  }

  static InvoiceSettings fromStorage() {
    final json = StorageService().getString('gep_invoice_settings');
    if (json.isNotEmpty) {
      try {
        final decoded = jsonDecode(json);
        if (decoded is Map<String, dynamic>) {
          return InvoiceSettings.fromJson(decoded);
        }
      } catch (_) {}
    }
    return const InvoiceSettings();
  }
}

final invoiceSettingsProvider = StateNotifierProvider<InvoiceSettingsNotifier, InvoiceSettings>((ref) {
  return InvoiceSettingsNotifier();
});

class InvoiceSettingsNotifier extends StateNotifier<InvoiceSettings> {
  InvoiceSettingsNotifier() : super(const InvoiceSettings()) {
    _load();
  }

  static const _key = 'gep_invoice_settings';

  void _load() {
    state = InvoiceSettings.fromStorage();
  }

  void save(InvoiceSettings settings) {
    state = settings;
    StorageService().setString(_key, jsonEncode(settings.toJson()));
  }
}
