import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import '../core/helpers.dart';
import '../providers/quote_provider.dart';

String formatQuoteText(List<QuoteEntry> items) {
  if (items.isEmpty) return 'No items.';

  final grouped = <String, List<QuoteEntry>>{};
  for (final item in items) {
    final key = item.client;
    grouped.putIfAbsent(key, () => []).add(item);
  }

  final buf = StringBuffer();
  buf.writeln('Survey Aide — Payments');
  buf.writeln('=' * 40);
  buf.writeln();

  for (final entry in grouped.entries) {
    buf.writeln('Client: ${entry.key}');
    if (entry.value.first.location.isNotEmpty) {
      buf.writeln('Location: ${entry.value.first.location}');
    }
    buf.writeln();
    double clientTotal = 0;
    for (final item in entry.value) {
      buf.writeln(serviceLabel(item.code, item.name));
      for (final line in item.lines) {
        buf.writeln('  ${line.label}: ${peso(line.amount)}');
      }
      final lineTotals = item.lines.fold<double>(0, (s, l) => s + l.amount);
      buf.writeln('  ${'=' * 20}');
      buf.writeln('  Subtotal: ${peso(lineTotals)}');
      buf.writeln();
      clientTotal += lineTotals;
    }
    buf.writeln('Client Total: ${peso(clientTotal)}');
    buf.writeln();
  }

  final grandTotal = items.fold<double>(0, (s, item) => s + item.lines.fold<double>(0, (ss, l) => ss + l.amount));
  buf.writeln('=' * 40);
  buf.writeln('GRAND TOTAL: ${peso(grandTotal)}');
  buf.writeln();
  buf.writeln('Generated by Survey Aide');

  return buf.toString();
}

Future<void> copyToClipboard(String text) async {
  await Clipboard.setData(ClipboardData(text: text));
}

Future<void> shareText(String text) async {
  await SharePlus.instance.share(ShareParams(text: text));
}

Future<Uint8List> generateQuoteImage(List<QuoteEntry> items) async {
  const double w = 600;
  const double headerH = 80;
  const double footerH = 40;
  const double lineH = 24;
  const double margin = 20;

  final grouped = <String, List<QuoteEntry>>{};
  for (final item in items) {
    grouped.putIfAbsent(item.client, () => []).add(item);
  }

  final rows = <String, String>{};
  double grandTotal = 0;
  for (final entry in grouped.entries) {
    rows['client_${entry.key}'] = 'Client: ${entry.key}';
    if (entry.value.first.location.isNotEmpty) {
      rows['loc_${entry.key}'] = 'Location: ${entry.value.first.location}';
    }
    rows['sp1_${entry.key}'] = '';
    double clientTotal = 0;
    for (final item in entry.value) {
      rows['svc_${item.uid}'] = serviceLabel(item.code, item.name);
      for (final l in item.lines) {
        rows['line_${item.uid}_${l.label}'] = '  ${l.label}: ${peso(l.amount)}';
      }
      final st = item.lines.fold<double>(0, (s, l) => s + l.amount);
      rows['sub_${item.uid}'] = '  Subtotal: ${peso(st)}';
      rows['sp2_${item.uid}'] = '';
      clientTotal += st;
    }
    rows['ctot_${entry.key}'] = 'Client Total: ${peso(clientTotal)}';
    rows['sp3_${entry.key}'] = '';
    grandTotal += clientTotal;
  }
  rows['grand'] = 'GRAND TOTAL: ${peso(grandTotal)}';

  final lineKeys = rows.keys.toList();
  final totalHeight = headerH + (lineKeys.length * lineH) + footerH + margin * 2;

  final recorder = ui.PictureRecorder();
  final canvas = Canvas(recorder, Rect.fromLTWH(0, 0, w, totalHeight));

  canvas.drawRect(Rect.fromLTWH(0, 0, w, totalHeight),
      Paint()..color = const Color(0xFFFBF9F2));
  canvas.drawRect(const Rect.fromLTWH(0, 0, w, headerH),
      Paint()..color = const Color(0xFFE8A06B));

  void drawText(String txt, double x, double y, {
    double size = 14, Color color = const Color(0xFF1A1E1D), ui.FontWeight? weight, bool center = false,
  }) {
    final pb = ui.ParagraphBuilder(
      ui.ParagraphStyle(
        textAlign: center ? ui.TextAlign.center : ui.TextAlign.left,
        fontSize: size,
        fontWeight: weight,
      ),
    )
      ..pushStyle(ui.TextStyle(color: color, fontSize: size, fontWeight: weight))
      ..addText(txt);
    final constraints = ui.ParagraphConstraints(width: center ? w : w - 2 * margin);
    final layout = pb.build()..layout(constraints);
    canvas.drawParagraph(layout, Offset(x, y));
  }

  drawText('Survey Aide', 0, 24, size: 24, color: const Color(0xFFFFFFFF), weight: FontWeight.bold, center: true);

  double y = headerH + margin;
  for (final key in lineKeys) {
    final txt = rows[key]!;
    final isGrand = txt.startsWith('GRAND');
    final isClient = txt.startsWith('Client') || txt.startsWith('GRAND');
    drawText(txt, margin, y,
      size: isGrand ? 16 : 14,
      color: isGrand ? const Color(0xFFC84A1E) : const Color(0xFF1A1E1D),
      weight: isClient ? FontWeight.bold : null,
    );
    y += lineH;
  }

  canvas.drawRect(Rect.fromLTWH(0, totalHeight - footerH, w, footerH),
      Paint()..color = const Color(0xFFE0DACB));
  drawText('Generated by Survey Aide', 0, totalHeight - footerH + 12,
      size: 12, color: const Color(0xFF6D6355), center: true);

  final picture = recorder.endRecording();
  final img = await picture.toImage(w.toInt(), totalHeight.toInt());
  final byteData = await img.toByteData(format: ui.ImageByteFormat.png);
  return byteData!.buffer.asUint8List();
}

Future<void> shareImage(Uint8List bytes) async {
  final dir = await getTemporaryDirectory();
  final file = File('${dir.path}/quote_receipt.png');
  await file.writeAsBytes(bytes);
  await SharePlus.instance.share(ShareParams(files: [XFile(file.path)]));
}

Future<void> sharePdf(List<QuoteEntry> items, {String fileName = 'invoice.pdf'}) async {
  final bytes = await generatePdfBytes(items);
  final dir = await getTemporaryDirectory();
  final file = File('${dir.path}/$fileName');
  await file.writeAsBytes(bytes);
  await SharePlus.instance.share(ShareParams(files: [XFile(file.path)]));
}

Future<Uint8List> generatePdfBytes(List<QuoteEntry> items) async {
  final pdf = pw.Document();
  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      header: (context) => pw.Container(
        color: const PdfColor.fromInt(0xFFE8A06B),
        padding: const pw.EdgeInsets.all(16),
        child: pw.Center(
          child: pw.Text('Survey Aide — Payments',
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 20, fontWeight: pw.FontWeight.bold)),
        ),
      ),
      footer: (context) => pw.Container(
        color: const PdfColor.fromInt(0xFFE0DACB),
        padding: const pw.EdgeInsets.all(8),
        child: pw.Text('Generated by Survey Aide',
          style: const pw.TextStyle(color: PdfColor.fromInt(0xFF6D6355), fontSize: 10)),
      ),
      build: (context) {
        final grouped = <String, List<QuoteEntry>>{};
        for (final item in items) {
          grouped.putIfAbsent(item.client, () => []).add(item);
        }

        final content = <pw.Widget>[];
        double grandTotal = 0;

        for (final entry in grouped.entries) {
          content.add(pw.SizedBox(height: 16));
          content.add(pw.Text('Client: ${entry.key}',
            style: const pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)));
          if (entry.value.first.location.isNotEmpty) {
            content.add(pw.Text('Location: ${entry.value.first.location}',
              style: const pw.TextStyle(fontSize: 12, color: PdfColor.fromInt(0xFF6D6355))));
          }
          content.add(pw.Divider());

          double clientTotal = 0;
          final rows = <pw.TableRow>[];

          for (final item in entry.value) {
            rows.add(pw.TableRow(
              children: [
                pw.Padding(padding: const pw.EdgeInsets.all(4), child: pw.Text(serviceLabel(item.code, item.name), style: const pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                pw.Padding(padding: const pw.EdgeInsets.all(4), child: pw.Text('')),
              ],
            ));
            for (final line in item.lines) {
              rows.add(pw.TableRow(
                children: [
                  pw.Padding(padding: const pw.EdgeInsets.only(left: 16, top: 2, bottom: 2), child: pw.Text(line.label)),
                  pw.Padding(padding: const pw.EdgeInsets.all(2), child: pw.Text(peso(line.amount), textAlign: pw.TextAlign.right)),
                ],
              ));
            }
            final st = item.lines.fold<double>(0, (s, l) => s + l.amount);
            rows.add(pw.TableRow(
              children: [
                pw.Padding(padding: const pw.EdgeInsets.only(left: 16, top: 4, bottom: 4), child: pw.Text('Subtotal', style: const pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                pw.Padding(padding: const pw.EdgeInsets.all(4), child: pw.Text(peso(st), textAlign: pw.TextAlign.right, style: const pw.TextStyle(fontWeight: pw.FontWeight.bold))),
              ],
            ));
            clientTotal += st;
          }

          content.add(pw.Table(
            border: pw.TableBorder.all(color: const PdfColor.fromInt(0xFFE0DACB)),
            children: rows,
          ));

          content.add(pw.SizedBox(height: 8));
          content.add(pw.Text('Client Total: ${peso(clientTotal)}',
            style: const pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)));
          grandTotal += clientTotal;
        }

        content.add(pw.SizedBox(height: 16));
        content.add(pw.Divider());
        content.add(pw.Text('GRAND TOTAL: ${peso(grandTotal)}',
          style: const pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColor.fromInt(0xFFC84A1E))));

        return content;
      },
    ),
  );

  return pdf.save();
}

Future<void> generatePdf(List<QuoteEntry> items) async {
  final bytes = await generatePdfBytes(items);
  final dir = await getTemporaryDirectory();
  final file = File('${dir.path}/quote_receipt.pdf');
  await file.writeAsBytes(bytes);
  await Printing.layoutPdf(onLayout: (_) => bytes);
}

Future<void> printPdf(List<QuoteEntry> items) async {
  final bytes = await generatePdfBytes(items);
  await Printing.layoutPdf(onLayout: (_) => bytes);
}
